### ISSUE TITLE
[Nyiur] Questions About Theme Features!

### ISSUE THREAD

**Issue by chanroll** [fukou/tumblr-theme#18]
Hi Fukou! 

First off, just want to say that I really love your theme! It's so unique and it looks great overall!

Just want to know how to add posts under the featured section? I tried adding the hashtag "featured" in one of my posts but it still won't appear under the featured section. 

Also, how can I be able to mimic the features attached below to my own version of your theme? 
Thank you!!! Hope to hear from you :>

<img width="600" alt="Screen Shot 2023-10-20 at 8 41 36 AM" src="https://github.com/fukou/tumblr-theme/assets/148440101/ccaf6abf-75c1-4aa7-988f-5537fc1315e3">

<img width="614" alt="Screen Shot 2023-10-20 at 8 41 53 AM" src="https://github.com/fukou/tumblr-theme/assets/148440101/9f552223-ad1f-4135-8f1f-2f29aa319ba2">

**Comment by fukou** [comment]
Hi @chanroll,

To better assist you in investigating the issue, would you mind providing your blog URL? This will allow me to take a look and see if there's something wrong with the theme.

As for your second question, I'm not quite sure what you mean. Are you looking to make the navigation link feature on the top match the styling of the bottom one on the Nyiur theme? Or do you have your own theme that you'd like to replicate?

**Comment by chanroll** [comment]
> Hi @chanroll,
> 
> To better assist you in investigating the issue, would you mind providing your blog URL? This will allow me to take a look and see if there's something wrong with the theme.
> 
> As for your second question, I'm not quite sure what you mean. Are you looking to make the navigation link feature on the top match the styling of the bottom one on the Nyiur theme? Or do you have your own theme that you'd like to replicate?

Hi! Sorry for the last reply I just saw your message. Here is my blog URL: https://hankekii.tumblr.com/

And as for the second question, sorry if it seemed unclear huhu I'm using your theme and I was just wondering how to make the navigation tab appear on my blog too! Can't seem to find it in the customization settings. Maybe I just overlooked it though.

**Comment by fukou** [comment]
Hi @chanroll!

The featured section is displayed correctly on my end 😁

![image](https://github.com/fukou/tumblr-theme/assets/19899840/32c46c0b-11c3-4728-8786-ebac0d3928e2)

I think the issue might be related to your current browser session still using the old cache, which could delay the changes from appearing immediately. To resolve this, **try performing a hard refresh and clearing your browser cache** 🤔💭

---

To make the navigation tab appear on your blog, please follow these steps: visit the customization post at https://nyiur-theme.tumblr.com/post/656291782790938624/about-this-theme. 

**You'll find the instructions under "How to add a custom link to this theme" (along with other instructions) 👍**

Once you've completed these steps, it should be displayed automatically! 
If the footer navigation bottom section still isn't showing up, please go to your customization page, locate the "Footer Navigation Visibility" dropdown, and change it to "Show."

![image](https://github.com/fukou/tumblr-theme/assets/19899840/77baa2e3-21d6-47a2-a291-bad1c35861bb)

Let me know if you have more questions!
Thank you.

**Comment by chanroll** [comment]
Hi! Thank you so much for your help. I’ll look into your suggestions! Might
not be able to browser cache because of the bookmarks i have on my computer
but hopefully hard refreshing will help.

Thank you again

**Comment by fukou** [comment]
Hi @chanroll 

No worries, just let me know if you have any more questions!
I will close this ticket now as resolved. Feel free to re-open the ticket if you'd like!

**Comment by chanroll** [comment]
Fukou hi! Just wanted to say that the Featured Page section is working on my end (don't know since when because I just opened my blog just now hehe). Thank you again!!! Means a lot. Your blog themes are really cool :">
