### ISSUE TITLE
[Empati Tamako] Can't view post in grid layout

### ISSUE THREAD

**Issue by wojenka** [fukou/tumblr-theme#24]
"View post" doesn't work. I noticed it yesterday after i posted more stuff on my blog. when i had 5 posts everything worked perfectly and now you can only view posts that are on the 2nd page (or last one since my blog has just two pages for now). I didn't edit html or css.

**Screenshots**
First page:
![image](https://github.com/fukou/tumblr-theme/assets/119942986/6ea329a7-29a7-40f1-b226-82b0b7fdb80f)
![image](https://github.com/fukou/tumblr-theme/assets/119942986/a7fd2137-2ded-41be-b540-c5aedc3d7f79)
> hover works however after clicking on view post nothing happens

Second page:
![image](https://github.com/fukou/tumblr-theme/assets/119942986/75222bcf-62fc-44e9-90bc-2b97e8111a71)
![image](https://github.com/fukou/tumblr-theme/assets/119942986/4fd82c66-f15c-4eb0-b85b-e63ea8ccd23b)
> after clicking "view post" the post is shown 

**Browsers**: Brave, Opera GX, Chrome 
Issue occurs not only for me but also for people who view my blog.

**Comment by fukou** [comment]
Hi @wojenka 

It'd be great if you could provide the URL of your affected blog as well. It's _hard_ for me to diagnose the issue without having direct access to your main blog. Luckily, I found your main blog with the same username as your GitHub and found it on https://flutterwar.tumblr.com/

Could you please temporarily set the blog layout back to "Grid" for me to re-check? Currently, your blog is set to a masonry layout (which doesn't help my case to re-check).

Thank you.

**Comment by wojenka** [comment]
Sorry for late response. I changed the layout back to grid. When I checked if viewing works it did on the first page but didn't work on the 2nd one. After deleting 3 latest posts (so there's the same amount of them as when I opened the issue) it doesn't work on the 1st page but works on the 2nd one like before.
Not sure if this information will be helpful or not.

**Comment by fukou** [comment]
This is indeed a bug 😅

After checking, the reason why the pop-up won't work is that it looks for the video post, but since there are none on the first page, it's somehow throwing an error in my code for the pop-up part.

I will revisit this issue when I am free (I will definitely let you know once it's fixed) 👍🏻

Thank you again for reporting the issue! I really appreciate it.

**Comment by fukou** [comment]
Hi @wojenka

The issue should be fixed now! You can reinstall the theme by replacing the code in your customizer with the new one [here](https://raw.githubusercontent.com/fukou/tumblr-theme/main/empati-theme/empati-theme.html).

---

Just in case you're curious, here are the fixes: https://github.com/fukou/tumblr-theme/pull/25. Silly me, I should have anticipated that by adding a fallback if the poster image is not available 😛

Thank you again for reporting; closing this issue now!

**Comment by wojenka** [comment]
Thank you kind coder!!! Have a nice day :)
